### ISSUE TITLE
Disregard certain fields when selecting

### ISSUE THREAD

**Issue by GSI** [jhawthorn/fzy#14]
When fuzzy searching paths, I find myself never typing first parts:

    /home/jh/documents/about-catz.txt
    /home/jh/downloads/donkey.png

If we **fzy** the string `"do"` in this example, we'd still get both lines as a result.

If we could tell fzy to **display** full lines, **but disregard parts** of the text upon selection - the first three directories in the hierarchy, in this case - it would be possible to just return a single result.

In fzf this would be done with `--delimiter='/' --with-nth=4..`, but maybe some other solution, like non-greedy regex would help too.
(Whatever causes less performance impact.)

**Comment by jhawthorn** [comment]
This could be confusing for a user because `/home/jh/documents/about-catz.txt` would be shown, but only the file name would be searchable.

I'd like to keep fzy's feature set minimal, and I don't fzy should know about parsing file paths or similar. Other programs are preferred to filter fzy's input and output for specific needs. It is The Unix Way.

For example, instead of

```
find /home/jh/documents | fzy --delimiter='/' --with-nth=4
```

One could do something like:
```
BASEPATH=/home/jh/documents
RELPATH=$(find "$BASEPATH" -printf "%P\n" | fzy -p "$BASEPATH> ")
echo "$BASEPATH/$RELPATH"
```

This gives us:

* A prompt with the cursor after `/home/jh/documents/> `, which makes it clear where we're searching
* The candidates only show the relative path from `/home/jh/documents`, which makes it clear what parts can be searched.


(afaik `%P` is a gnu find extension, but the same could likely be done in a portable way with `cd`)
