### ISSUE TITLE
fzy: either allow -q to have no argument or accept any string as -q

### ISSUE THREAD

**Issue by gauteh** [jhawthorn/fzy#15]
I am trying to set up an alias like:
```
alias fzyfind=find . | fzy
```

but if I want to start with a query I have to specify the `-q`option, and I cannot add it to the alias because then I cannot use the alias without specifying a start query.

Is the -q option necessary? Could not the argument that is not an option just always be the intital query?

**Comment by jhawthorn** [comment]
I think it is best if an argument is required. It's weird that `-q` would "work" but have no meaning. However, `-q` can accept an empty string as an argument. 

You should be able to achieve what you want using a shell function instead of an alias

```
fzyfind() {
  find . | fzy -q "$*"
}
```

This uses any arguments to fzyfind as input to `-q`. If none are provided it is equivalent to `-q ""`

`fzyfind` -> `find . | fzy -q ""`
`fzyfind foo` -> `find . | fzy -q "foo"`
`fzyfind foo bar` -> `find . | fzy -q "foo bar"`

**Comment by gauteh** [comment]
John Hawthorn writes on juni 5, 2016 9:51:
> I think it is best if an argument is required. It's weird that `-q` would "work" but have no meaning. However, `-q` can accept an empty string as an argument. 
> 

Right, that works of course :)
