### ISSUE TITLE
Custom ctrl-p match function

### ISSUE THREAD

**Issue by renstrom** [jhawthorn/fzy#37]
It would be nice to be able to combine the ctrl-p with fzy. The awesome fuzziness of fzy with the nice Vim integration of ctrl-p. I imagine it would be possible by creating a custom [`g:ctrlp_match_func`](https://github.com/ctrlpvim/ctrlp.vim/blob/master/doc/ctrlp.txt#L791-L825). However my Vimscript knowledge is super poor, so I was kind of looking for help on the matter.

Feel free to close though if you feel this isn't relevant to fzy as a project. But I figured since you mention Vim integration (and ctrl-p) in the README, it might be worth a shot to ask.

**Comment by ohjames** [comment]
@renstrom neovim-fuzzy is a good alternative.

**Comment by gfairchild** [comment]
I use neovim-fuzzy and confirm it's great. Here's how I've configured it:

```
nnoremap <C-p> :FuzzyOpen<CR>
let g:fuzzy_opencmd = 'tabnew'
```

**Comment by jhawthorn** [comment]
Fzy is more of a replacement of ctrl-p than an add on. See the [Use with vim](https://github.com/jhawthorn/fzy#use-with-vim) section of the readme

**Comment by casr** [comment]
The below is just informational and the ticket can remain closed but:

  * Aside from its fuzzy find engine, Ctrl-P offers pre-baked functions for file, buffer, mru, tag searches and comes with a plugin community already. Just swapping out the engine to something superior like fzy mean we can get the rest for free.
  * The snippet from the README works well in Vim but the Neovim project made some changes to whatever happens in the `system` command so that the experience seems really sluggish. It works just about but really poorly. There is [this ticket](https://github.com/neovim/neovim/issues/1044) about it on their tracker and it seems pretty complicated to make it work nicely in Neovim.
  * For some reason, perhaps I am crazy, I am trying to make my `vimrc` compatible with both Neovim and Vim. I am lacking a nice fuzzy finder that works well between both. Using `g:ctrlp_match_func` strikes me a good idea that has the nice benefit of having a fall back to pure Vimscript if fzy/terminal isn't available (i.e. different system/GUI session). I may in the future make a stab at trying to write it because the employment opportunities for people with Vimscript knowledge are crazy high.
