### ISSUE TITLE
unit test fails in i386 platform

### ISSUE THREAD

**Issue by czchen** [jhawthorn/fzy#38]
See https://bugs.debian.org/860207, it has the following error during build in i386 platform.

```

...
   dh_auto_test -a
	make -j4 test
make[1]: Entering directory '/«PKGBUILDDIR»'
cc -g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -g -std=c99 -O3 -pedantic  -Isrc -o test/fzytest test/fzytest.c src/match.o src/choices.o -lpthread
./test/fzytest
test "test_exact_scores" failed
   assert(match("a", "*a") == SCORE_GAP_LEADING) was false
   at test/fzytest.c:81

14 tests, 80 assertions, 1 failures
Makefile:28: recipe for target 'check' failed
make[1]: *** [check] Error 1
```

**Comment by jhawthorn** [comment]
Hi @czchen. Thanks so much for including `fzy` to debian. Please let me know if there's anything I can do to aid in package maintenance.

This issue should be fixed in [Version 0.9](https://github.com/jhawthorn/fzy/releases/tag/0.9), which I've just released. The issue was simply that I should not have been doing `==` to test floats. I now [test with a tolerance](https://github.com/jhawthorn/fzy/commit/43b8f4e75a32d4b14bd16259af600e1364d68821), which should fix the architectures it was failing on (verified in a debian i386 qemu). The test suite has also had a major overhaul in this release and now gives better errors.
