### ISSUE TITLE
Exit fzy, exit script.

### ISSUE THREAD

**Issue by larryhynes** [jhawthorn/fzy#44]
Hi

If I'm using `fzy` in a script, and I `CTRL-C` to abort, I would like to exit the script. Currently, `fzy` aborts, but the script continues.

Example:

```
#!/bin/sh

file=$(echo 'foo' | fzy)

cp "$file" ~/
```

`CTRL-C` while `fzy` is displaying 'foo' passes 'foo' to the `cd` command.

I currently work around this using, for example:

```
#!/bin/sh

file=$(echo 'foo' | fzy)
case "$?" in
	0) : ;;
	1) exit 1 ;;
esac

cp "$file" ~/
```

In this case, `CTRL-C` while `fzy` is displaying 'foo' will abort the script.

(It occurs to me that `CTRL-C` is undocumented, and maybe you're not interested?)

**Comment by bendem** [comment]
I'm going to take a wild stab in the dark and say if you use bash instead of sh the problem will not happen as bash will abort your script if a command fails.

If if doesn't, `set -eo pipefail` will make sure your script exits when a command fails (tbf, all your scripts should start with `set -euo pipefail`).

**Comment by larryhynes** [comment]
Thanks. I'm using dash, but `set -e` (for errexit; there's no 'pipefail' in dash) does the trick nicely.
